version: "3"

services:
  db:
    image: mysql:5.7.37
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - ./init/mysql.sql:/docker-entrypoint-initdb.d/setup.sql

  acra:
    image: "cossacklabs/acra-server:${ACRA_DOCKER_IMAGE_TAG:-0.92.0}"
    # Restart server after correct termination, for example after the config
    # was changed through the API
    depends_on:
      #   - acra-keymaker_server
      - db
    ports:
      - "9393:9393"
    environment:
      # INSECURE!!! You MUST define your own ACRA_MASTER_KEY
      # The default is only for testing purposes
      ACRA_MASTER_KEY: ${ACRA_MASTER_KEY:-UHZ3VUNNeTJ0SEFhbWVjNkt4eDdVYkc2WnNpUTlYa0E=}
    volumes:
      - ./.acrakeys/acra-server:/keys
      # Directory with configuration, rewriteable
      - ./acra/configs:/config
    command: >-
      --encryptor_config_file=/config/encryptor_config.yaml
      --poison_detect_enable=true
      --poison_shutdown_enable=true
      --keys_dir=/keys
      --db_host=db
      --db_port=3306
      --client_id=acro_demo
      --mysql_enable
